version: "3.7"
services:
  frontend:
    build:
      context: ./NeLtech-front
      dockerfile: Dockerfile
    container_name: neltech_front
    restart: unless-stopped
    ports: 
      - "5173:5173"
    working_dir: /app
    networks:
      - neltech
    expose:
      - "5173"
    deploy:
      replicas: 1
    depends_on:
      - backend  
  backend:
    build:
      context: ./NeLtech-back
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    deploy:
      replicas: 3
    depends_on:
      - db
    networks:
      - neltech
    expose:
      - "8000"
  haproxy:
    build:
      context: ./haproxy
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - neltech
    expose:
      - 8000
  db:
    image: mysql:8.0
    container_name: neltech_db
    restart: unless-stopped
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: neltech
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes: 
      - laravel-db:/data/db
    deploy:
      replicas: 1
    networks:
      - neltech
    expose:
      - 3306
  nginx-reverse:
    image: nginx:latest
    volumes: 
      - ./nginx/web.conf:/etc/nginx/nginx.conf
    ports:
      - "1234:1234"
    depends_on:
      - frontend
      - backend
    networks:
      - neltech
    expose:
      - 1234
  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "80:80"
    deploy:
      replicas: 1
    networks:
      - neltech
    expose:
      - 80
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports: 
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

networks:
 neltech:
    driver: bridge
volumes:
  laravel-db:
  grafana-storage: {}
  prom_data:
