version: "3.7"
services:
  frontend:
    build:
      context: ./NeLtech-front
      dockerfile: Dockerfile
    container_name: neltech_front
    restart: unless-stopped
    ports: 
      - "5173:5173"
    working_dir: /app
    networks:
      - neltech
    expose:
      - "5173"
    depends_on:
      - backend  
  backend:
    build:
      context: ./NeLtech-back
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    restart: unless-stopped
    working_dir: /var/www
    depends_on:
      - db
    networks:
      - neltech
    expose:
      - 8000    
  db:
    image: mysql:8.0
    container_name: neltech_db
    restart: unless-stopped
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: neltech
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes: 
      - laravel-db:/data/db
    networks:
      - neltech
    expose:
      - 3306
  nginx-reverse:
    image: nginx:latest
    container_name: neltech_nginx
    volumes: 
      - ./nginx/web.conf:/etc/nginx/nginx.conf
    ports:
      - "1234:1234"
    depends_on:
      - frontend
      - backend
    networks:
      - neltech
    expose:
      - 1234
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: neltech_phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "80:80"
    networks:
      - neltech
    expose:
      - 80
networks:
 neltech:
    driver: bridge
volumes:
  laravel-db:
